version: "3"
services:
  host:
    container_name: playground-host
    networks:
      - playground-network
    image: nginx:alpine
    volumes:
      - ../public:/var/www/public
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "db"
    depends_on:
      - "db"
    ports:
      - "8080:80"
  
  app:
    container_name: playground-app
    user: ${HOST_UID}:${HOST_GID}
    networks:
      - playground-network
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/var/www
      - ./php/conf.d/xdebug-dev.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - "db"
    depends_on:
      - "db"    
    working_dir: /var/www
  
  db:
    container_name: playground-database
    networks:
      - playground-network
    image: 'postgres:14.3-alpine'
    volumes:
        - playground-db:/var/lib/postgresql/data
    environment:
        CONTAINER_ROLE: db
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE}
    ports:
        - "54320:5432"

volumes:
  playground-db:

networks:
  playground-network: